version: '3.5'

services:
  nginx:
    image: nginx:1.21-alpine
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      APP_PORT: "3000"
      CLIENT_GW_URL: "http://95.217.162.140:8080/"
    depends_on:
      - web

  web:
    build: .
    env_file:
      - .env

